name: ci
on:
  push:
    branches:
      - main
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  BUILD_NUMBER: ${{ github.run_number }}
  IMAGE_NAME: myapp
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
          
      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_NUMBER }} .
          
      - name: Push Docker Image
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_NUMBER }}

  update-deployment:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CD repo
        uses: actions/checkout@v3
        with:
          repository: muammeraliarpa/cd
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          path: cd-repo
          
      - name: Update deployment.yaml
        run: |
          cd cd-repo
          sed -i "s|image: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:.*|image: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_NUMBER }}|g" deployment.yaml
          
      - name: Commit and push changes
        run: |
          cd cd-repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add deployment.yaml
          git commit -m "Update image tag to ${{ env.BUILD_NUMBER }}" || exit 0
          git push
