name: ci

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  BUILD_NUMBER: ${{ github.run_number }}
  IMAGE_NAME: myapp

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_NUMBER }} .

      - name: Push Docker Image
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_NUMBER }}
 
  imageTag-updater:
    runs-on: ubuntu-latest
    needs: build-and-push
    
    steps:
      - name: Checkout CD repo
        uses: actions/checkout@v3
        with:
          repository: muammeraliarpa/cd
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Update imageTag
        uses: cheelim1/image-updater@v1.11
        with:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          REPO_NAME: 'cd'
          REPO_OWNER: 'muammeraliarpa'
          FILE_PATH: 'deployment.yaml'  
          IMAGE_TAG: ${{ env.BUILD_NUMBER }}

